### ISSUE TITLE
Event should allow for symmetric modification of edges

### ISSUE THREAD

**Issue by jacksonhenry3** [jacksonhenry3/CDT#17]
Ideally there would be functions in the Event object that allow for modification of left right past and future that behave symmetrically for their connected counter parts. I.E.event.set_left(another event) would set both event.left and event.left.right ) IDK if it's possible but maybe we could even use the syntax "event.left =another event" and this would automatically update "another event.right" to be event.

**Comment by JWKennington** [comment]
After discussing, we want to remove subtle behavior modifications inside __setattr__ in favor of explicit module-level utility functions. Also, switch to @property methods instead of subtle __getattr__
