### ISSUE TITLE
Push pop broken

### ISSUE THREAD

**Issue by jacksonhenry3** [jacksonhenry3/CDT#28]
when popping and then immediately pushing a subspace from space-time some edges are doubled up which can be seen by the darker blue edges.

![image](https://user-images.githubusercontent.com/1857496/108636962-9aea7c00-7456-11eb-90f5-55b9ffb7a95c.png)

**Comment by JWKennington** [comment]
There's a commit in #27 that fixes this, ensures uniqueness of temporal connections

**Comment by jacksonhenry3** [comment]
I may be confused, but i believe this error was produced in the most recent commit of that branch. The code is 
``` python
random.seed(93345)
size = 10
st = generate_flat_spacetime(size, size)
n = st.get_random_node()
st.push(st.pop([n]))
plot_st.plot_2d(st, labels=True)
```

where line 232 in plot_st has been modified to have 
```python
edges_past_pointing, color=(0, 0, 1, .5), antialiaseds=True, linewidth=2,
```
to show the overlap.

**Comment by JWKennington** [comment]
Hm, unable to reproduce on my end. Added more tests for uniqueness of temporal connections.
When you run your code, did you try running an explicit check at the end? Something like this, BC it seems that nodes 24 and 34 are doubly-connected from your plot:

```python
st.node_future[24]
```

**Comment by jacksonhenry3** [comment]
The problem is just with the past pointing edges. And st.node_past[35] gives [24, 25, 24]

*revision, actually my test can't tell if its just past. That would be very odd. Ill do further tests,

**Comment by JWKennington** [comment]
I added some tools for examining these things more precisely: if you run the below code, you will see the diff table, where the 'left' column shows what the attribute of the first argument (`cdt1`) was, and the 'right' column shows that of the second argument (`cdt2`):

```python
from cdtea.tests.test_space_time import find_duplicate_temporal_connections, spacetime_diff, format_diff
random.seed(93345)
size = 10
st = space_time.generate_flat_spacetime(size, size)
st2 = space_time.generate_flat_spacetime(size, size)
n = st.get_random_node()
st.push(st.pop([n]))
spacetime_diff(st, st2, display_results=True)
```

```
SpaceTime Diff Summary:

0 Unique L Nodes: set()
0 Unique R Nodes: set()
100 Common Nodes: [(0, 99)]

Diff Table:
```
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>Node</th>
      <th>Type</th>
      <th>Left</th>
      <th>Right</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>2</td>
      <td>past</td>
      <td>[92, 91]</td>
      <td>[91, 92]</td>
    </tr>
    <tr>
      <td>3</td>
      <td>future</td>
      <td>[14, 13]</td>
      <td>[13, 14]</td>
    </tr>
    <tr>
      <td>12</td>
      <td>past</td>
      <td>[2, 1]</td>
      <td>[1, 2]</td>
    </tr>
    <tr>
      <td>12</td>
      <td>future</td>
      <td>[23, 22]</td>
      <td>[22, 23]</td>
    </tr>
    <tr>
      <td>13</td>
      <td>future</td>
      <td>[24, 23]</td>
      <td>[23, 24]</td>
    </tr>
    <tr>
      <td>14</td>
      <td>past</td>
      <td>[4, 3]</td>
      <td>[3, 4]</td>
    </tr>
    <tr>
      <td>23</td>
      <td>future</td>
      <td>[34, 33]</td>
      <td>[33, 34]</td>
    </tr>
    <tr>
      <td>24</td>
      <td>past</td>
      <td>[14, 13]</td>
      <td>[13, 14]</td>
    </tr>
  </tbody>
</table>

The above results seem to indicate that the *only* reason that the two CDTs aren't equivalent is because of the order of the future / past edges. However, the order in the list doesn't actually mean anything, since for example, left/right in the list of future nodes doesn't correspond to left/right in the spatial slice. I think we should switch to using sets for future/past node collections

**Comment by jacksonhenry3** [comment]
I just finished testing and found that the future and past nodes that differ for the given example are as follow
Futures with repeats
1 [11, 12, 12]
4 [14, 14, 15]
91 [1, 2, 2]
92 [2, 2, 3, 3]
93 [3, 3, 4]
Pasts with repeats
22 [11, 12, 12]
25 [14, 14, 15]
33 [22, 23, 23]
34 [23, 23, 24, 24]
35 [24, 24, 25]

I'll also stash my changes and do a fresh pull in case something i did messed with it.

**Comment by JWKennington** [comment]
I'm unable to get dups. For instance when I run `st.node_past[35]` I just get `[24, 25]`. I think its a good idea for you to pull the branch fresh and try again

**Comment by jacksonhenry3** [comment]
OK, I'm on the same page as you now, IDK what could have happened, i only really modified the visualization. I'll have to pick apart my changes in more detail later. Thanks for the help.

**Comment by JWKennington** [comment]
no worries at all - this digging uncovered another improvement we can make #29
