### ISSUE TITLE
Syntactic sugar for node manipulation inelegant and possibly error prone

### ISSUE THREAD

**Issue by jacksonhenry3** [jacksonhenry3/CDT#3]
not sure the right way to implement this, the "node_object" class is very helpful for changing standard phrasing from self.node_future[node_index] to node_obj.future which is more easily readable. I don't like that it returns node indices and not node objects.  I also allow it to be initialized without full information so it can be used to create new nodes, but this is dangerous because we could try to add an incomplete node or modify the space_time without properly updating all parameters.

**Comment by JWKennington** [comment]
Resolved by #4
