### ISSUE TITLE
once a dilatonis added move and inverse move are not inverse

### ISSUE THREAD

**Issue by jacksonhenry3** [jacksonhenry3/CDT#30]
interestingly, once there is a dillaton, beouse the addition of new faces will mean a new random dilaton value, move and inverse move are no longer inverse. Is this a physics problem? have we accidentally restricted (or more likely biased?) the space we can visit?
 This is why
```python
test_functional_inverses
```
can't include
```python
assert dst == dst_copy
```

we actually only want to assert that they are geometrical inverses.

**Comment by JWKennington** [comment]
this is easily accomplished by adding a method `SpaceTime.geometric_equal` that compares elements of the representative dictionary that correspond to geometric features. We can then update the test. I anticipate this taking at most 3 lines of code

Should we rename move / inverse move? something like "forward" "backward", or "increase" and "decrease". We could then also rename the lengthy `modifications` module name to `moves`? just a thought
